//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CpCafeteria.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CpCafeteria.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap add_25dp_000000_FILL0_wght400_GRAD0_opsz24 {
            get {
                object obj = ResourceManager.GetObject("add_25dp_000000_FILL0_wght400_GRAD0_opsz24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap add_circle_25dp_000000_FILL0_wght400_GRAD0_opsz24 {
            get {
                object obj = ResourceManager.GetObject("add_circle_25dp_000000_FILL0_wght400_GRAD0_opsz24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ChatGPT_Image_20_may_2025__10_22_50_a_m_ {
            get {
                object obj = ResourceManager.GetObject("ChatGPT Image 20 may 2025, 10_22_50 a.m.", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ChatGPT_Image_20_may_2025__10_35_46_a_m_ {
            get {
                object obj = ResourceManager.GetObject("ChatGPT Image 20 may 2025, 10_35_46 a.m.", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ChatGPT_Image_20_may_2025__10_35_46_a_m__removebg_preview {
            get {
                object obj = ResourceManager.GetObject("ChatGPT_Image_20_may_2025__10_35_46_a.m.-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ChatGPT_Image_21_may_2025__09_58_34_a_m_ {
            get {
                object obj = ResourceManager.GetObject("ChatGPT Image 21 may 2025, 09_58_34 a.m.", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ChatGPT_Image_21_may_2025__09_58_34_a_m__removebg_preview {
            get {
                object obj = ResourceManager.GetObject("ChatGPT_Image_21_may_2025__09_58_34_a.m.-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap check_box_outline_blank_25dp_434343_FILL0_wght400_GRAD0_opsz24 {
            get {
                object obj = ResourceManager.GetObject("check_box_outline_blank_25dp_434343_FILL0_wght400_GRAD0_opsz24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap close_25dp_434343_FILL0_wght400_GRAD0_opsz24 {
            get {
                object obj = ResourceManager.GetObject("close_25dp_434343_FILL0_wght400_GRAD0_opsz24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap delete_25dp_000000_FILL0_wght400_GRAD0_opsz24 {
            get {
                object obj = ResourceManager.GetObject("delete_25dp_000000_FILL0_wght400_GRAD0_opsz24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit_25dp_000000_FILL0_wght400_GRAD0_opsz24 {
            get {
                object obj = ResourceManager.GetObject("edit_25dp_000000_FILL0_wght400_GRAD0_opsz24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap horizontal_rule_25dp_434343_FILL0_wght400_GRAD0_opsz24 {
            get {
                object obj = ResourceManager.GetObject("horizontal_rule_25dp_434343_FILL0_wght400_GRAD0_opsz24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap list_35 {
            get {
                object obj = ResourceManager.GetObject("list_35", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lupa1 {
            get {
                object obj = ResourceManager.GetObject("lupa1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lupa2 {
            get {
                object obj = ResourceManager.GetObject("lupa2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lupa3 {
            get {
                object obj = ResourceManager.GetObject("lupa3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lupa4 {
            get {
                object obj = ResourceManager.GetObject("lupa4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap minimize_25dp_434343_FILL0_wght600_GRAD0_opsz24 {
            get {
                object obj = ResourceManager.GetObject("minimize_25dp_434343_FILL0_wght600_GRAD0_opsz24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap minimize_25dp_434343_FILL0_wght600_GRAD0_opsz24___copia {
            get {
                object obj = ResourceManager.GetObject("minimize_25dp_434343_FILL0_wght600_GRAD0_opsz24 - copia", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap restaurant_25dp_FFEFD5_FILL0_wght400_GRAD0_opsz24 {
            get {
                object obj = ResourceManager.GetObject("restaurant_25dp_FFEFD5_FILL0_wght400_GRAD0_opsz24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap select_window_2_25dp_434343_FILL0_wght400_GRAD0_opsz24 {
            get {
                object obj = ResourceManager.GetObject("select_window_2_25dp_434343_FILL0_wght400_GRAD0_opsz24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
